services:
  minecraft:
    image: itzg/minecraft-server
    container_name: mc_server
    ports:
      - "25565:25565"
      - "25575:25575"
    environment:
      EULA: "TRUE"
      MEMORY: "10G"
      VERSION: "1.21.6"
      ONLINE_MODE: "TRUE"
      MOTD: "((-))"
      ALLOW_NETHER: "TRUE"
      RCON_PASSWORD: "123"
      RCON_PORT: 25575
      VIEW_DISTANCE: 15
      ENABLE_WHITELIST: "TRUE"
      DIFFICULTY: "HARD"
      TYPE: "FABRIC"
    volumes:
      - ./data:/data
      - ./mod:/mod
    restart: unless-stopped

  bot:
    build: .
    container_name: mc_discord_bot
    depends_on:
      - minecraft
    environment:
      TZ: Europe/Amsterdam
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      RCON_HOST: ${RCON_HOST}
      RCON_PORT: ${RCON_PORT}
      RCON_PASSWORD: ${RCON_PASSWORD}
      LOG_FILE_PATH: ${LOG_FILE_PATH}
      PUBLIC_SERVER_IP: ${PUBLIC_SERVER_IP}
      PUBLIC_SERVER_PORT: ${PUBLIC_SERVER_PORT}
      SERVER_OPENINGS_TIME: ${SERVER_OPENINGS_TIME}
      SERVER_CLOSING_TIME: ${SERVER_CLOSING_TIME}
    volumes:
      - ./data:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
